---
title: "lab3b_lorenestasiuk"
author: "Lorene Stasiuk"
date: "9/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

```{r}
download.file(url = "https://ndownloader.figshare.com/files/2292169", destfile = "data/portal_data_joined.csv")
```

```{r}
survey <- read_csv("data/portal_data_joined.csv")
```


```{r, selectcolumns}
### To select columns of a data frame, use select(). The first argument to this function is the data frame (surveys), and the subsequent arguments are the columns to keep.
select(survey, plot_id, species_id, weight)

### To select all columns except certain ones, put a “-” in front of the variable to exclude it.
select(survey, -record_id, -species_id)

### To choose rows based on a specific criterion, use filter():
filter(survey, year == 1995)

```

```{r, pipes}
### create a temporary data frame and use that as input to the next function
surveys2 <- filter(survey, weight < 5)
surveys_sml <- select(surveys2, species_id, sex, weight)


### Pipes let you take the output of one function and send it directly to the next
survey %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

```

```{r, challenge1}
### Using pipes, subset the surveys data to include animals collected before 1995 and retain only the columns year, sex, and weight.

survey %>%
    filter(year < 1995) %>%
    select(year, sex, weight)
```


```{r, mutate}
### To create a new column of weight in kg:
survey %>%
  mutate(weight_kg = weight / 1000)

### You can also create a second new column based on the first new column within the same call of mutate():
survey %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)

### If this runs off your screen and you just want to see the first few rows, you can use a pipe to view the head() of the data.
survey %>%
  mutate(weight_kg = weight / 1000) %>%
  head()

### The first few rows of the output are full of NAs, so if we wanted to remove those we could insert a filter() in the chain:
survey %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()

```

```{r, challenge2}
### Create a new data frame from the surveys data that meets the following criteria: contains only the species_id column and a new column called hindfoot_cm containing the hindfoot_length values converted to centimeters. In this hindfoot_cm column, there are no NAs and all values are less than 3.
surveys_hindfoot_cm <- survey %>%
    filter(!is.na(hindfoot_length)) %>%
    mutate(hindfoot_cm = hindfoot_length / 10) %>%
    filter(hindfoot_cm < 3) %>%
    select(species_id, hindfoot_cm)

```

```{r, summarize}
### To compute the mean weight by sex:
survey %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))

### You can also group by multiple columns:
survey %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE)) %>% 
  tail()

### Because the missing values are removed first, we can omit na.rm = TRUE when computing the mean:
survey %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight))

### Using the print() function
survey %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print(n = 15)


### We could add a column indicating the minimum weight for each species for each sex:
survey %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))

### We can sort on min_weight to put the lighter species first:
survey %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)


### To sort in descending order, we need to add the desc() function. If we want to sort the results by decreasing order of mean weight:
survey %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(desc(mean_weight))

```

```{r, counting}
### If we wanted to count the number of rows of data for each sex, we would do:
survey %>%
    count(sex)

### surveys %>% count() is equivalent to:
survey %>%
    group_by(sex) %>%
    summarise(count = n())

### For convenience, count() provides the sort argument:
survey %>%
    count(sex, sort = TRUE) 

### If we wanted to count combination of factors, such as sex and species, we would specify the first and the second factor as the arguments of count():
survey %>%
  count(sex, species) 

### With the above code, we can proceed with arrange() to sort the table according to a number of criteria so that we have a better comparison. We might want to arrange the table above in (i) an alphabetical order of the levels of the species and (ii) in descending order of the count:
survey %>%
  count(sex, species) %>%
  arrange(species, desc(n))


```

```{r, challenge3}
### 1. How many animals were caught in each plot_type surveyed?
survey %>%
    count(plot_type)

### 2. Use group_by() and summarize() to find the mean, min, and max hindfoot length for each species (using species_id). Also add the number of observations (hint: see ?n).
survey %>%
    filter(!is.na(hindfoot_length)) %>%
    group_by(species_id) %>%
    summarize(
        mean_hindfoot_length = mean(hindfoot_length),
        min_hindfoot_length = min(hindfoot_length),
        max_hindfoot_length = max(hindfoot_length),
        n = n()
    )

### What was the heaviest animal measured in each year? Return the columns year, genus, species_id, and weight.
survey %>%
    filter(!is.na(weight)) %>%
    group_by(year) %>%
    filter(weight == max(weight)) %>%
    select(year, genus, species, weight) %>%
    arrange(year)


```

```{r, reshape}
### Let’s use spread() to transform surveys to find the mean weight of each genus in each plot over the entire survey period. We use filter(), group_by() and summarise() to filter our observations and variables of interest, and create a new variable for the mean_weight.

surveys_gw <- survey %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))

str(surveys_gw)

### This yields surveys_gw where the observations for each plot are spread across multiple rows, 196 observations of 3 variables.
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)

str(surveys_spread)


### We could now plot comparisons between the weight of genera in different plots, although we may wish to fill in the missing values first.
surveys_gw %>%
  spread(genus, mean_weight, fill = 0) %>%
  head()

```

```{r, gathering}
### To recreate surveys_gw from surveys_spread we would create a key called genus and value called mean_weight and use all columns except plot_id for the key variable. Here we exclude plot_id from being gather()ed.
surveys_gather <- surveys_spread %>%
  gather(key = "genus", value = "mean_weight", -plot_id)

str(surveys_gather)

```

```{r,challenge4}
### 1. Spread the surveys data frame with year as columns, plot_id as rows, and the number of genera per plot as the values. You will need to summarize before reshaping, and use the function n_distinct() to get the number of unique genera within a particular chunk of data. It’s a powerful function! See ?n_distinct for more.
surveys_spread_genera <- survey %>%
  group_by(plot_id, year) %>%
  summarize(n_genera = n_distinct(genus)) %>%
  spread(year, n_genera)

head(surveys_spread_genera)

### 2. Now take that data frame and gather() it again, so each row is a unique plot_id by year combination.
surveys_spread_genera %>%
  gather("year", "n_genera", -plot_id)

### 3. The surveys data set has two measurement columns: hindfoot_length and weight. This makes it difficult to do things like look at the relationship between mean values of each measurement per year in different plot types. Let’s walk through a common solution for this type of problem. First, use gather() to create a dataset where we have a key column called measurement and a value column that takes on the value of either hindfoot_length or weight.
surveys_long <- survey %>%
  gather("measurement", "value", hindfoot_length, weight)

### 4. With this new data set, calculate the average of each measurement in each year for each different plot_type. Then spread() them into a data set with a column for hindfoot_length and weight. Hint: You only need to specify the key and value columns for spread().
surveys_long %>%
  group_by(year, measurement, plot_type) %>%
  summarize(mean_value = mean(value, na.rm=TRUE)) %>%
  spread(measurement, mean_value)


```

```{r, exportiongdata}
### Let’s start by removing observations of animals for which weight and hindfoot_length are missing, or the sex has not been determined:
surveys_complete <- survey %>%
  filter(!is.na(weight),           # remove missing weight
         !is.na(hindfoot_length),  # remove missing hindfoot_length
         !is.na(sex))                # remove missing sex

### Because we are interested in plotting how species abundances have changed through time, we are also going to remove observations for rare species. First we are going to create a data set that counts how often each species has been observed, and filter out the rare species; then, we will extract only the observations for these more common species:

## Extract the most common species_id
species_counts <- surveys_complete %>%
    count(species_id) %>% 
    filter(n >= 50)

## Only keep the most common species
surveys_complete <- surveys_complete %>%
  filter(species_id %in% species_counts$species_id)

### To make sure that everyone has the same data set, check that surveys_complete has 30463 rows and 13 columns by typing 
dim(surveys_complete)

### Now that our data set is ready, we can save it as a CSV file in our data folder.
write_csv(surveys_complete, path = "data/surveys_complete.csv")

```

Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].

# REFERENCES
```
@Misc{Chang2015,
  Title                    = {shiny: Web Application Framework for R. R package version 0.12.1},

  Author                   = {Chang, W. and Cheng, J. and Allaire, JJ. and Xie, Y. and McPherson, J. },
  Year                     = {2015},

  Type                     = {Computer Program},
  Url                      = {http://CRAN.R-project.org/package=shiny}
}

@Article{RCoreTeam,
  Title                    = {R: A Language and Environment for Statistical Computing},
  Author                   = {{R Core Team}},
  Year                     = {2015},

  Type                     = {Journal Article},
  Url                      = {http://www.R-project.org}
}
```

