---
title: "lab3a_lorenestasiuk"
author: "Lorene Stasiuk"
date: "9/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

```{r}
download.file(url = "https://ndownloader.figshare.com/files/2292169", destfile = "data/portal_data_joined.csv")
```


```{r}
survey <- read.csv("data/portal_data_joined.csv")
```


```{r, top}
### check the top of this data frame using the function head()
head(survey)
```


```{r, inspect_structure}
str(survey)
```

```{r, challenge1}
### Based on the output of str(surveys), can you answer the following questions?

### 1. What is the class of the object surveys?
## * data frame

### 2. How many rows and how many columns are in this object?
## * number of rows: 34786, number of columns: 13

### 3. How many species have been recorded during these surveys?
## * number of species: 48
```

```{r, indexing}
### Indexing and subsetting data frames

# first three elements in the 7th column (as a vector)
survey[1:3, 7] 
# the 3rd row of the data frame (as a data.frame)
survey[3, ]    
# equivalent to head_surveys <- head(surveys)
head_surveys <- survey[1:6, ] 
```

```{r, use_-_sign}
### You can also exclude certain indices of a data frame using the “-” sign

survey[-(7:34786), ] # Equivalent to head(surveys)
```

```{r, challenge2}
### 1. Create a data.frame (surveys_200) containing only the data in row 200 of the surveys dataset.

survey_200 <- survey[200, ]

### 2. Notice how nrow() gave you the number of rows in a data.frame?
# Use that number to pull out just that last row in the data frame.
# Compare that with what you see as the last row using tail() to make sure it’s meeting expectations.
# Pull out that last row using nrow() instead of the row number.
# Create a new data frame (surveys_last) from that last row.

# Saving `n_rows` to improve readability and reduce duplication

n_rows <- nrow(survey)
survey_last <- survey[n_rows, ]

### 3. Use nrow() to extract the row that is in the middle of the data frame. Store the content of this row in an object named surveys_middle.

surveys_middle <- survey[n_rows / 2, ]

### 4. Combine nrow() with the - notation above to reproduce the behavior of head(surveys), keeping just the first through 6th rows of the surveys dataset.

surveys_head <- survey[-(7:n_rows), ]

```

```{r, factor}
sex <- factor(c("male", "female", "female", "male"))

levels(sex)
nlevels(sex)

sex # current order

sex <- factor(sex, levels = c("male", "female"))
sex # after re-ordering
```

```{r, convert_factor}
### Convert a factor to a character vector

as.character(sex)

### Another method is to use the levels() function. Compare:

year_fct <- factor(c(1990, 1983, 1977, 1998, 1990))
as.numeric(levels(year_fct))[year_fct]    # The recommended way.
```

```{r, renaming_factors}
### Let’s look at the number of males and females captured over the course of the experiment:

## bar plot of the number of females and males captured during the experiment:
plot(as.factor(survey$sex))

sex <- factor(survey$sex)
head(sex)

levels(sex)

levels(sex)[1] <- "undetermined"
levels(sex)

head(sex)
```


```{r, challenge3}
### Rename “F” and “M” to “female” and “male” respectively.
levels(sex)[2:3] <- c("female", "male")

### Now that we have renamed the factor level to “undetermined”, can you recreate the barplot such that “undetermined” is last (after “male”)?
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(sex)
```

```{r, strignsasfactors}
## Compare the difference between our data read as `factor` vs `character`.
survey <- read.csv("data/portal_data_joined.csv", stringsAsFactors = TRUE)
str(survey)
survey <- read.csv("data/portal_data_joined.csv", stringsAsFactors = FALSE)
str(survey)
## Convert the column "plot_type" into a factor
survey$plot_type <- factor(survey$plot_type)
```

```{r, challegne4}
### We have seen how data frames are created when using read.csv(), but they can also be created by hand with the data.frame() function. There are a few mistakes in this hand-crafted data.frame. Can you spot and fix them? Don’t hesitate to experiment!

animal_data <- data.frame(animal = c("dog", "cat", "sea cucumber", "sea urchin"), feel = c("furry", "furry", "squishy", "spiny"), weight = c(45, 8, 1.1, 0.8))

### Can you predict the class for each of the columns in the following example? Check your guesses using str(country_climate):
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c("10", "30", "18", "15"),
       northern_hemisphere = c("TRUE", "TRUE", "FALSE", "FALSE"),
       has_kangaroo = c("FALSE", "FALSE", "FALSE", "TRUE")
       )
str(country_climate)
```


Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].

# REFERENCES
```
@Misc{Chang2015,
  Title                    = {shiny: Web Application Framework for R. R package version 0.12.1},

  Author                   = {Chang, W. and Cheng, J. and Allaire, JJ. and Xie, Y. and McPherson, J. },
  Year                     = {2015},

  Type                     = {Computer Program},
  Url                      = {http://CRAN.R-project.org/package=shiny}
}

@Article{RCoreTeam,
  Title                    = {R: A Language and Environment for Statistical Computing},
  Author                   = {{R Core Team}},
  Year                     = {2015},

  Type                     = {Journal Article},
  Url                      = {http://www.R-project.org}
}
```
